export const WORDS = [
  {
    en: "tool",
    ru: "инструмент",
  },
  {
    en: "us",
    ru: "как",
  },
  {
    en: "I",
    ru: "Я",
  },
  {
    en: "his",
    ru: "его",
  },
  {
    en: "that",
    ru: "тот",
  },
  {
    en: "he",
    ru: "он",
  },
  {
    en: "was",
    ru: "был",
  },
  {
    en: "for",
    ru: "для",
  },
  {
    en: "on",
    ru: "на",
  },
  {
    en: "are",
    ru: "являются",
  },
  {
    en: "with",
    ru: "с",
  },
  {
    en: "be",
    ru: "быть",
  },
  {
    en: "at",
    ru: "на",
  },
  { en: "one", ru: "один" },
  { en: "have", ru: "иметь" },
  { en: "this", ru: "это" },
  { en: "from", ru: "из" },
  { en: "by", ru: "от" },
  { en: "hot", ru: "горячий / жарко" },
  { en: "word", ru: "слово" },
  { en: "but", ru: "но" },
  { en: "what", ru: "что" },
  { en: "some", ru: "некоторый" },
  { en: "is", ru: "является" },
  { en: "it", ru: "это" },
  { en: "you", ru: "ты" },
  { en: "or", ru: "или" },
  { en: "had", ru: "имел" },
  { en: "the of", ru: "из / о" },
  { en: "to", ru: "в / к" },
  { en: "and", ru: "и" },
  { en: "in", ru: "в" },
  { en: "we", ru: "мы" },
  { en: "can", ru: "может" },
  { en: "out", ru: "из / вне" },
  { en: "other", ru: "другой" },
  { en: "were", ru: "были" },
  { en: "which", ru: "который" },
  { en: "do", ru: "делать" },
  { en: "their", ru: "их" },
  { en: "time", ru: "время" },
  { en: "if", ru: "если" },
  { en: "will", ru: "будет" },
  { en: "how", ru: "как" },
  { en: "said", ru: "говорить" },
  { en: "an each", ru: "каждый" },
  { en: "tell", ru: "говорить" },
  { en: "does", ru: "делает" },
  { en: "set", ru: "задавать / комплект" },
  { en: "three", ru: "три" },
  { en: "want", ru: "хотеть" },
  { en: "air", ru: "воздух" },
  { en: "well", ru: "хорошо" },
  { en: "also", ru: "также" },
  { en: "play", ru: "играть" },
  { en: "small", ru: "маленький" },
  { en: "end", ru: "конец" },
  { en: "put", ru: "ставить" },
  { en: "home", ru: "дом" },
  { en: "read", ru: "читать" },
  { en: "hand", ru: "рука" },
  { en: "port", ru: "порт" },
  { en: "large", ru: "большой" },
  { en: "spell", ru: "читать по буквам / орфография" },
  { en: "add", ru: "добавлять" },
  { en: "even", ru: "даже" },
  { en: "land", ru: "земля" },
  { en: "here", ru: "здесь" },
  { en: "must", ru: "должен" },
  { en: "big", ru: "большой" },
  { en: "high", ru: "высокий" },
  { en: "such", ru: "такой" },
  { en: "follow", ru: "следовать" },
  { en: "act", ru: "действовать" },
  { en: "why", ru: "почему" },
  { en: "ask", ru: "спрашивать" },
  { en: "men", ru: "люди" },
  { en: "change", ru: "менять" },
  { en: "went", ru: "отправился" },
  { en: "light", ru: "свет / легкий" },
  { en: "kind", ru: "добрый / разновидность" },
  { en: "off", ru: "от / выключенный" },
  { en: "need", ru: "необходимость" },
  { en: "house", ru: "дом" },
  { en: "picture", ru: "картина / фото" },
  { en: "try", ru: "пробовать / пытаться" },
  { en: "us", ru: "нас" },
  { en: "again", ru: "снова" },
  { en: "animal", ru: "животное" },
  { en: "point", ru: "точка" },
  { en: "mother", ru: "мать" },
  { en: "world", ru: "мир" },
  { en: "near", ru: "близко" },
  { en: "build", ru: "строить" },
  { en: "self", ru: "себя" },
  { en: "earth", ru: "земля" },
  { en: "father", ru: "отец" },
  { en: "any", ru: "любой" },
  { en: "new", ru: "новый" },
  { en: "work", ru: "работа" },
  { en: "part", ru: "часть" },
  { en: "take", ru: "брать" },
  { en: "get", ru: "получать" },
  { en: "place", ru: "место" },
  { en: "made", ru: "сделать" },
  { en: "live", ru: "жить" },
  { en: "where", ru: "где" },
  { en: "after", ru: "после" },
  { en: "back", ru: "назад" },
  { en: "little", ru: "немного" },
  { en: "only", ru: "только" },
  { en: "round", ru: "круглый / вокруг" },
  { en: "man", ru: "мужчина" },
  { en: "year", ru: "год" },
  { en: "came", ru: "пришел" },
  { en: "show", ru: "показывать" },
  { en: "every", ru: "каждый" },
  { en: "good", ru: "хороший" },
  { en: "me", ru: "мне" },
  { en: "give", ru: "давать" },
  { en: "our", ru: "наш" },
  { en: "under", ru: "под" },
  { en: "name", ru: "имя" },
  { en: "very", ru: "очень" },
  { en: "through", ru: "через" },
  { en: "just", ru: "только / просто" },
  { en: "form", ru: "вид, форма / образовывать" },
  { en: "sentence", ru: "предложение" },
  { en: "great", ru: "отличный" },
  { en: "think", ru: "думать" },
  { en: "say", ru: "говорить" },
  { en: "help", ru: "помогать, помощь" },
  { en: "low", ru: "низкий" },
  { en: "line", ru: "линия, черта" },
  { en: "differ", ru: "отличаться" },
  { en: "turn", ru: "поворачивать" },
  { en: "cause", ru: "причина" },
  { en: "much", ru: "много" },
  { en: "mean", ru: "значить / подлый / средний" },
  { en: "before", ru: "до" },
  { en: "move", ru: "двигать" },
  { en: "right", ru: "право / верный" },
  { en: "boy", ru: "мальчик" },
  { en: "old", ru: "старый" },
  { en: "too", ru: "тоже" },
  { en: "same", ru: "также" },
  { en: "she", ru: "она" },
  { en: "all", ru: "все" },
  { en: "there", ru: "там" },
  { en: "when", ru: "когда" },
  { en: "up", ru: "вверх / подниматься" },
  { en: "use", ru: "использовать" },
  { en: "your", ru: "твой" },
  { en: "way", ru: "путь" },
  { en: "about", ru: "о" },
  { en: "many", ru: "много" },
  { en: "then", ru: "затем" },
  { en: "them", ru: "их" },
  { en: "write", ru: "писать" },
  { en: "would", ru: "бы / было бы" },
  { en: "like", ru: "нравиться" },
  { en: "so", ru: "так" },
  { en: "these", ru: "эти" },
  { en: "her", ru: "ее" },
  { en: "long", ru: "долго /длинный" },
  { en: "make", ru: "делать" },
  { en: "thing", ru: "вещь" },
  { en: "see", ru: "видеть" },
  { en: "him", ru: "его" },
  { en: "two", ru: "два /двое" },
  { en: "has", ru: "имеет" },
  { en: "look", ru: "смотреть / взгляд" },
  { en: "more", ru: "больше" },
  { en: "day", ru: "день" },
  { en: "could", ru: "мог" },
  { en: "go", ru: "идти" },
  { en: "come", ru: "приходить" },
  { en: "did", ru: "сделал" },
  { en: "number", ru: "номер" },
  { en: "sound", ru: "звук" },
  { en: "no", ru: "нет" },
  { en: "most", ru: "самый / большинство" },
  { en: "people", ru: "люди" },
  { en: "my", ru: "мой" },
  { en: "over", ru: "над" },
  { en: "know", ru: "знать" },
  { en: "water", ru: "вода" },
  { en: "than", ru: "чем" },
  { en: "call", ru: "звонить / звонок" },
  { en: "first", ru: "первый" },
  { en: "who", ru: "кто" },
  { en: "may", ru: "может" },
  { en: "down", ru: "вниз" },
  { en: "side", ru: "сторона" },
  { en: "been", ru: "был" },
  { en: "now", ru: "сейчас" },
  { en: "find", ru: "найти" },
];
